# Generated by Django 5.0.4 on 2024-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone_number',
            field=models.CharField(default=1, help_text="Please provide organizer's contact number.", max_length=10, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
