# Generated by Django 5.0.4 on 2024-05-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverimage',
            old_name='event_type',
            new_name='event_category',
        ),
    ]
