# Generated by Django 5.0.4 on 2024-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0002_rename_event_type_coverimage_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='additional_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
