# Generated by Django 5.0.4 on 2024-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0003_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
