# Generated by Django 5.0.4 on 2024-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0003_category_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_data',
            field=models.JSONField(default={}),
        ),
    ]
