# Generated by Django 5.0.4 on 2024-05-31 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0006_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
