# Generated by Django 5.0.6 on 2024-06-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0010_alter_event_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='birthday_person_age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='birthday_person_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bride_age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bride_father_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bride_mother_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bride_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='dress_code',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gift_sending_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groom_age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groom_father_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groom_mother_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groom_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='guest_of_honor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_pin_code',
        ),
        migrations.AddField(
            model_name='event',
            name='aditional_fields',
            field=models.JSONField(default={}, verbose_name='Fields'),
        ),
    ]
