# Generated by Django 5.0.4 on 2024-05-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0010_alter_coverimage_image'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingcard',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_creator',
        ),
        migrations.AddField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('BirthdayParty', 'Birthday Party'), ('WeddingCard', 'Wedding Card')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BirthdayParty',
        ),
        migrations.DeleteModel(
            name='WeddingCard',
        ),
    ]
