# Generated by Django 5.0.6 on 2024-06-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0011_remove_event_birthday_person_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='aditional_fields',
            new_name='additional_fields',
        ),
    ]
