# Generated by Django 5.0.4 on 2024-05-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0011_remove_weddingcard_event_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_category',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_category', to='WeddingApp.category'),
        ),
    ]
