# Generated by Django 5.0.4 on 2024-05-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0014_remove_event_content_type_remove_event_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='celebrant_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='RSVP_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='event',
            name='guest_of_honor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bride_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='wedding_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groom_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rsvp_deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_template',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='event',
            name='message',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rsvp_response',
        ),
        migrations.CreateModel(
            name='BirthdayParty',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WeddingApp.event')),
                ('celebrant_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=100)),
                ('RSVP_email', models.EmailField(max_length=254)),
                ('cover_photo', models.ImageField(upload_to='birthday_covers/')),
                ('max_guests', models.PositiveIntegerField(default=50)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gift_registry_link', models.URLField(blank=True, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('WeddingApp.event',),
        ),
        migrations.CreateModel(
            name='InaugurationEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WeddingApp.event')),
                ('guest_of_honor', models.CharField(max_length=100)),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_contact', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('max_guests', models.PositiveIntegerField(default=200)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inauguration_date', models.DateField()),
                ('venue_address', models.CharField(max_length=200)),
            ],
            bases=('WeddingApp.event',),
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WeddingApp.event')),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('RSVP_email', models.EmailField(max_length=254)),
                ('cover_photo', models.ImageField(upload_to='wedding_covers/')),
                ('max_guests', models.PositiveIntegerField(default=100)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('honeymoon_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('wedding_registry_link', models.URLField(blank=True, null=True)),
            ],
            bases=('WeddingApp.event',),
        ),
    ]
