# Generated by Django 5.0.6 on 2024-06-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0015_alter_category_category_image_alter_coverimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_cover_image', to='WeddingApp.coverimage'),
            preserve_default=False,
        ),
    ]
