# Generated by Django 5.0.4 on 2024-05-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0015_remove_event_age_remove_event_celebrant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayparty',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='birthdayparty',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='inaugurationevent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inaugurationevent',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='honeymoon_destination',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='ticket_price',
        ),
    ]
