# Generated by Django 5.0.6 on 2024-06-18 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0018_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
