# Generated by Django 5.0.6 on 2024-06-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0019_event_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_category_type', to='WeddingApp.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_cover_image', to='WeddingApp.coverimage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_category', to='WeddingApp.category'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='WeddingApp.category'),
        ),
    ]
