# Generated by Django 5.0.6 on 2024-06-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0021_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Sub_category', to='WeddingApp.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.BooleanField(default=False),
        ),
    ]
