# Generated by Django 5.0.6 on 2024-07-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0023_event_event_id_group_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=255, verbose_name='Event ID'),
        ),
    ]
