# Generated by Django 5.0.6 on 2024-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0025_group_owner_userprofile_dob_userprofile_occasion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_published',
        ),
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private Event'),
        ),
    ]
