# Generated by Django 5.0.6 on 2024-07-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0026_remove_event_is_published_event_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone'),
        ),
    ]
