# Generated by Django 5.0.6 on 2024-07-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0028_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
